### ISSUE TITLE
Make server name field optional and fill default IP

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#100]
Currently in Android application server name field is mandatory (when adding new server). Probably it will be more useful to make it optional and fill it equal to host address if user left it empty. 

Also it would be nice to set some default IP like "192.168.1.1" as host address due to transmission server often installed somewhere in local network.

**Comment by 6c65726f79** [comment]
> Probably it will be more useful to make it optional and fill it equal to host address if user left it empty.

You're totally right, it will be much easier to add a server quickly. I'll add this is the next version.

> Also it would be nice to set some default IP like "192.168.1.1" as host address due to transmission server often installed somewhere in local network.

I'm not sure about this one, it's hard to say which IP is the most commonly used as local server IP, and this may vary from user to user. So i'm not planning to set a default IP for now, but I am always open to suggestions!

Thank you for your interest in the project!

**Comment by 6c65726f79** [comment]
Changes applied in [v1.1.4](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.4)
