### ISSUE TITLE
Add "move" option to torrent context menu

### ISSUE THREAD

**Issue by tilda** [6c65726f79/Transmissionic#1000]
**Describe the feature you'd like**
I'd like to see an option in the context menu for torrents to move them to another path. The vanilla Transmission web UI has this already so shouldn't be too hard to implement, hopefully.

**Describe a visual implementation**
![image](https://user-images.githubusercontent.com/8301262/179361049-9a704ae9-b7ed-4ccb-bcfb-f78a1cca1381.png)
(Not sure "Move data" is the best term, but gets the job done for a mockup really)
Ideally the resulting dialog from clicking the button would be either a text field with the current location pre-filled or a file explorer of sorts.

**Additional context**
*N/A*

**Comment by 6c65726f79** [comment]
Hi,

Thank you for your suggestion. It's already possible to move the torrent data from the details modal, but I'll add this option in the context menu of the torrent list like you've suggested.

**Comment by 6c65726f79** [comment]
Feature added in [v1.7.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.0), thank you again for your suggestion.
