### ISSUE TITLE
Not adding a second server

### ISSUE THREAD

**Issue by ivanmalyshev** [6c65726f79/Transmissionic#1025]
Good afternoon!
Transmissionic runs on a separate virtual machine. The local transfer daemon has been added, but cannot add a separate server. Areas with authorization are inactive.
What am I doing wrong?
![image](https://user-images.githubusercontent.com/68625959/184351129-ca7d74a1-fb29-44cd-98e2-c7db37a3f447.png)

**Comment by 6c65726f79** [comment]
Hi,

Currently, it is not possible to save your credentials in the web ui for security reasons. I'll try to find a solution for the next version. You can also use the desktop version.

**Comment by 6c65726f79** [comment]
You can't connect to another host from the web ui, you need to use the desktop version.
