### ISSUE TITLE
IP-API doesn't work when Transmission web is served via HTTPS

### ISSUE THREAD

**Issue by oresot** [6c65726f79/Transmissionic#1059]
When accessing Transmission on my NAS via HTTPS it fails to get the IP Country via ip-api.com. 

The Firefox console shows the message:
`Blocked loading mixed active content “http://ip-api.com/json/{{ip}}?fields=16387&lang=en-US”`

It seems that the related code tries to load HTTPS when Transmissionic is served that way:
https://github.com/6c65726f79/Transmissionic/blob/acd24be1a26bd90645899fea7e6e73ff3be33731/src/services/Utils.ts#L134

But ip-api.com returns this via HTTPS:
```
❯ curl "https://ip-api.com/json/9.9.9.9?fields=16386"
{"status":"fail"}
```

According to the documentation: https://ip-api.com/docs/api:json

> SSL (HTTPS)
> 
> 256-bit SSL encryption is not available for this free API. Please see our [pro service](https://members.ip-api.com/).

Could it be possible to define a reverse proxy URL via configuration or default.json? 
Otherwise, are other free alternatives considered? For example: http://country.is/  

```
❯ curl https://api.country.is/9.9.9.9
{"country":"US","ip":"9.9.9.9"}
```

**Comment by 6c65726f79** [comment]
Fixed in [v1.7.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.0), thank you for reporting it! I'll try to use an offline solution in a future version.
