### ISSUE TITLE
Browser needs cache reset to show new webui

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#109]
Testcase:
1. Delpoy webui v1.1.3, make sure that version in about window
2.  Delpoy webui v1.1.4, open about window - it shows version 1.1.3

**Comment by depler** [comment]
Hmm... something strange, only needs to refresh page. No big deal.

**Comment by 6c65726f79** [comment]
Yes, the cache can break some things when updating, use CTRL+F5 after updating to delete the cache and reload the page.
