### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by lucasmz1** [6c65726f79/Transmissionic#1112]
how do I set the server for download torrents? I'm sorry I am newbie.

**Comment by 6c65726f79** [comment]
Hi, please clarify your question, I'm not sure to understand. You want to select the server on which to add a new torrent?

**Comment by lucasmz1** [comment]
yes that's it. how do I creat a server ? can you give me a set up ?

**Comment by 6c65726f79** [comment]
This project is only a remote for [Transmission](https://transmissionbt.com/), so you need to install it first. Then you just have to enable remote access in Transmission settings. If both are running on the same device, you can leave all input fields empty in the "Server details" of Transmissionic.
