### ISSUE TITLE
Shifting speed info to new line

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#112]
Sometimes during downloading appears such effect with shifting speed info to new line and hiding ratio and total size. May be just put speed info on the left (in two lines) and other info on the right? I mean constantly.

![IMG_20210403_210424](https://user-images.githubusercontent.com/13541699/113487340-347a6400-94c0-11eb-95ef-55743b747c6a.jpg)

**Comment by 6c65726f79** [comment]
The total size on the right shouldn't disapear, normally only the ratio should be elipsed. I will try to fix this in the next version, thanks for reporting this.

**Comment by 6c65726f79** [comment]
And the speed information on two lines is useful only on small screen, as there is enough space on large screen to display it on one line. This allow to have two lines for the torrent name.

**Comment by 6c65726f79** [comment]
Fixed in [v1.1.6](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.6), now lines are truncated if they are too long.
