### ISSUE TITLE
Priority cannot be set to normal

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#113]
Test case:
1. Set high or low priority for file, save changes
2. Try to set normal priority for that file

Result: nothing happens when setting normal priority

**Comment by 6c65726f79** [comment]
Yes I've noticed it, this is already fixed by 66fb382, this will take effect in the next version. Thanks anyway.

**Comment by 6c65726f79** [comment]
Fixed in [v1.1.6](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.6)
