### ISSUE TITLE
Unable to set and report the status of LPD correctly

### ISSUE THREAD

**Issue by TianZerL** [6c65726f79/Transmissionic#1131]
**Describe the bug**
Transmissionic seems unable to set and report the status of LPD correctly, at least in transmission 3.0. 
I am using transmission and transmissionic via this docker [image](https://hub.docker.com/r/linuxserver/transmission/).

**To Reproduce**
1. Go to `Network` in `Server configuration`, and toggle `Local peer discovery(LPD)` option `ON`, and save it.
2. Refresh Transmissionic's web page or restart the APP, check `LPD` option again, it will become `OFF`.
3. Check `LPD` via other remote APP or web, or restart transmission and directly check the `settings.json`, will find LPD is `OFF`. (Seems Transmissionic did not enable it correctly?)
4. Enable `LPD` by other APP or directly set in `settings.json`, restart transmission and use Transmissionic to check LPD option.
5. Transmissionic reports LDP is still `OFF`, but other APP reports that LDP has enabled.

**Platform:**
 - OS: Windows11 (Web), Android 11(Web and APP)
 - Browser: chrome, edge

**Comment by TianZerL** [comment]
https://github.com/6c65726f79/Transmissionic/blob/99b2f4900ef1490b3ae8d592b9c4ba9897f06f91/src/views/ServerConfig.vue#L339
I think I found the problem. A typo caused the problem.

**Comment by 6c65726f79** [comment]
Thanks for pointing this out and correcting it! You're right, there was a typo I hadn't noticed. The new version will be available in the next few weeks.

**Comment by 6c65726f79** [comment]
Fixed in [v1.7.1](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.1), thank you again for your contribution!
