### ISSUE TITLE
Pause the Queue

### ISSUE THREAD

**Issue by SteffanCline** [6c65726f79/Transmissionic#1137]
Perhaps I missed it but is there an option to pause the queue/all downloads? 

If not, can an option be added to do this? This comes in handy in situations when the app can keep collecting torrents by automation but downloads paused so bandwidth can be used elsewhere at the moment.

**Comment by 6c65726f79** [comment]
Hi, thank you for your interest in this project.

You can already use the context menu to select all torrents and stop them all. You can also use the filters to select only queued torrents. Does this meet your needs?

**Comment by SteffanCline** [comment]
No, that doesn't help because new torrents come in and suck up the bandwidth while the others are still stopped/paused. In the app, there's an option to pause the queue and exists in some of the other themes I've seen. It's a very handy feature.
