### ISSUE TITLE
Need filter when choosing what to download

### ISSUE THREAD

**Issue by shenmo7192** [6c65726f79/Transmissionic#1163]
**Describe the feature you'd like**
Add a file filter when add a torrent and choose what to download

**Describe a visual implementation**
![图片](https://user-images.githubusercontent.com/47873776/196634312-cd611e5b-bc80-4223-a74b-7799931cbb6c.png)

**Additional context**
It cost me tons of time to just unselect those .zip file in my torrent.....That is painful

**Comment by 6c65726f79** [comment]
HI, thank you for your suggestion. I'll try to add it in the next version, this could be useful.

**Comment by 6c65726f79** [comment]
Feature added in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0).
