### ISSUE TITLE
Transmission v4

### ISSUE THREAD

**Issue by RihanArfan** [6c65726f79/Transmissionic#1187]
**Describe the feature you'd like**
Transmission v4 beta is now out and a noticeable improvement to web is:
> The remote control GUIs (transmission-qt and transmission-web) now use the RPC API "table" mode, resulting in smaller payloads / less bandwidth use.

(https://github.com/transmission/transmission/releases)

**Additional context**
I'm not sure whether Transmissionic can benefit from this API mode, but I figured I'd mention it. 😃

**Comment by 6c65726f79** [comment]
Hi, thank you for your suggestion! I'll do some tests to see if it's worth using this mode. But Transmissionic already uses the `recently-active` mode to drastically reduce bandwidth usage by refreshing only active torrents.

**Comment by XxUnkn0wnxX** [comment]
since V4.0 the folder has been renemed from web to `public_html` on the macos build
so you need to emty the conents of the web folder for Transmissionic in there now..

**Comment by 6c65726f79** [comment]
I've finally tested the table mode. With 1000 torrents, the RPC response is 77.1 kB in normal mode, and 68.7 kB in table mode, which doesn't make a huge difference, but it's still a 10% decrease so I implemented this feature.

> since V4.0 the folder has been renemed from web to `public_html`

Thank you for pointing this out.

**Comment by 6c65726f79** [comment]
Feature added in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0).
