### ISSUE TITLE
option to show Trackers directly

### ISSUE THREAD

**Issue by jiangjiangflies** [6c65726f79/Transmissionic#1203]
Hi,
Could you add an option to show trackers directly on the left side ?  Currently I have to click the Tracker dropdown menu to see all the trackers.  
There can be a CheckBox beside **Tracker** and **Filter**. When checked, trackers and torrents stats can display as default.  Unchecked, they will be hidden. 
I think it will be very nice to have such options.
![微信图片_20221117180433](https://user-images.githubusercontent.com/16556935/202418529-e28030fa-a62e-42c8-926a-9fe4a81514f4.png)

**Comment by 6c65726f79** [comment]
Hi, feature added in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0), thank you for suggesting it!
