### ISSUE TITLE
When renaming a file, automatically select the filename in the text input

### ISSUE THREAD

**Issue by jackbanh** [6c65726f79/Transmissionic#1226]
**Describe the feature you'd like**
When a user chooses to rename a file and it prompts for the new file name, it would be great if keyboard focus automatically jumped to the filename input field and if the current filename was automatically selected.

**Describe a visual implementation**
![rename file](https://user-images.githubusercontent.com/20655241/212155830-9ed3ac0b-4d1e-406c-81e0-467fdb707c87.png)

**Additional context**

**Comment by 6c65726f79** [comment]
Feature added in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0), thank you for suggesting it!
