### ISSUE TITLE
Transmissionic v1.7.1 displaying wrong bandwidth limits

### ISSUE THREAD

**Issue by steponmepls** [6c65726f79/Transmissionic#1244]
**Describe the bug**
App reports bigger speed values than what it's set in the `settings.json` file

**To Reproduce**
1. Stop the daemon and set down/up speed limits to 5000 and 2000 respectively 
2. Start the daemon
3. Connect to the daemon with the app and open `Limits` tab in `Server configuration`
4. See error (values set to 40000 and 16000)

**Platform:**
 - OS: Android 11

**Comment by 6c65726f79** [comment]
That's because the speed is displayed in bit/s instead of byte/s in Transmissionic, you can disable "Display speed in bit/s" in the settings.
