### ISSUE TITLE
Changing queue position

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#125]
Is it possible to sort torrents by queue position and change that position in the list? Transgui able to do this, but didn't find any controls for that here.

**Comment by 6c65726f79** [comment]
I'll try to add this, for the sorting it will be easy, but I need to find an intuitive way to add the option to update the position.

**Comment by 6c65726f79** [comment]
Feature added in [v1.1.7](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.7), thank you for your suggestion!

**Comment by depler** [comment]
Looks cool, thanks!

**Comment by 6c65726f79** [comment]
I'm reopening the issue because this feature needs some improvements.
