### ISSUE TITLE
Country detect not work in firefox

### ISSUE THREAD

**Issue by abubaca4** [6c65726f79/Transmissionic#1250]
Country detect not work in firefox

Open web ui in firefox
Enable country detect in settings
Open non empty peer list

 - OS: Tested in Windows 10, linux, android
 - Browser: Firefox 109.0.1

**Comment by 6c65726f79** [comment]
Fixed in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0), thank you for reporting it!
