### ISSUE TITLE
Copy/paste

### ISSUE THREAD

**Issue by Neifab** [6c65726f79/Transmissionic#1251]
Hello,

It's impossible to paste anything in the password field when adding a remote connection, and with a very strong password from a manager it's quite complicated.

Thanks

**Comment by 6c65726f79** [comment]
Hello, which platform do you use? If you're on desktop, you can use the keyboard shortcut to paste.

**Comment by 6c65726f79** [comment]
Fixed in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0), thank you for reporting it!
