### ISSUE TITLE
Unable to add authentication using web gui

### ISSUE THREAD

**Issue by aptonline** [6c65726f79/Transmissionic#126]
I'm using the latest web gui via MacOS and I can successfully add server but not the authentication details.  They are greyed out and won't allow input.

![screenshot](https://user-images.githubusercontent.com/190136/114297700-173e2a80-9aaa-11eb-9cc0-bb692212e635.png)

**Comment by 6c65726f79** [comment]
This is mainly for security reason, as it's not recommanded to use browsers to store plaintext credentials. But also because you need to be authenticated to load the Web UI, so you will still need to enter your credentials before loading the Web UI.

But if you still need this feature, you can inspect the inputs with the Dev Tools and remove the "disabled" attribute.

**Comment by aptonline** [comment]
Ok so I tried to add this to the linuxserver docker version of Transmission (https://github.com/linuxserver/docker-transmission) and placed the files in the `/config` folder (which is mapped to the container) and set the `TRANSMISSION_WEB_HOME` to `/config/transmissionic/`.  The UI loads correctly but it won't allow me to add the server.  Is Transmissionic similar to kettu and combustion-release or am I missing something?

**Comment by 6c65726f79** [comment]
Yes it should work like any other Web UI, if it's not the case I will try to fix this. I've never tested with a Docker installation so maybe i'm missing something.

What's the problem when you add a server? And are the Web UI and RPC accessible from the same host and port? Otherwide there may be CORS problems.

**Comment by aptonline** [comment]
The webui is accessible from the port I have set (in this case 8889) but if I try and access `/transmission/rpc/` I get the following:

``` 
409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: VinWJxkpPMwa8nEAIqC8uUdzWMHtHXDYAGVMG2fvjT1xEB3p
```

**Comment by 6c65726f79** [comment]
Ok perfect, this normal. Did you get the same error if you access `/transmission/rpc` without the last slash?
If no, set your RPC path to `/transmission/rpc/` in the server details, it should work.

**Comment by aptonline** [comment]
I get the same response with or without the `/`.

**Comment by 6c65726f79** [comment]
So the problem doesn't come from there, did you get any error in the Web UI?

I don't understand where exactly your problem is, at which step it doesn't work?

**Comment by aptonline** [comment]
Ok so I think I have this working.  It was totally user error, I entered the port in the wrong part of the UI when adding the server :(.  Sorry for the confusion.

For those looking to setup transmissionic with `llinuxserver/docker-transmission` place the tranmissionic webui folder in the config folder that you mapped to the container.  Name the folder anything you want (I called it transmissionic) and then add `- e TRANSMISSION_WEB_HOME = /config/transmissionic/` to your docker command.

Unlike other webui's don't forget to add the server details of your transmission container (correctly) for it to work.

**Comment by 6c65726f79** [comment]
Ok no problem, I'm glad you solved your problem. Thank you for sharing the solution.

So it doesn't work if you leave all inputs empty in the server details? The port and address should be automatically detected.

**Comment by aptonline** [comment]
Looks like I was wrong and you were right (again), just removed my server details and it automatically set the `Default` to the correct server settings.  I have amended my post above.

**Comment by 6c65726f79** [comment]
Well, I have to admit that this part is not well documented, you couldn't have guessed that. I will try to make this more clear.

Thank you for your feedback!
