### ISSUE TITLE
Can support paste multiple urls/magnets?

### ISSUE THREAD

**Issue by caibingcheng** [6c65726f79/Transmissionic#1267]
**Describe the feature you'd like**
Users can paste multiple download urls/magnets one time.

**Describe a visual implementation**
No button or anything else will be added, just support parse some formated multi-lines urls/magnets in the 'add' button.

**Additional context**
Users can paste multi-line here.
<img width="196" alt="image" src="https://user-images.githubusercontent.com/15170019/219875369-2cdda4b2-e5a3-4d8a-87b1-354c6d66203a.png">

**Comment by 6c65726f79** [comment]
Added in [v1.8.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.8.0), thank you for your suggestion!
