### ISSUE TITLE
Speed in KB/s

### ISSUE THREAD

**Issue by typhoon71** [6c65726f79/Transmissionic#1387]
**Describe the feature you'd like**
I see there's the _useBits_ boolean option. I'd like a _UseKB_ kind of option, to have the speed shown in KB/s.

**Describe a visual implementation**
Show all speeds in KB/s in the interface if the _UseKB_ is set to True (defaults to False).

**Additional context**
For consistency among my software and greater flexibility.
Just a minor detail, I use trasmissionic webUI and like it a lot.

**Comment by remlio** [comment]
it always been there. just switch it off and get the speed shown in KB/s.

![IMG_6539](https://github.com/user-attachments/assets/e69962ac-85a3-4939-a4ee-790976ce844d)

**Comment by typhoon71** [comment]
I knew about that option, but it's not behaving how I asked - at least when I last used the webUI.
Nest time I fire up the rpi I'll see if things work.

**Comment by remlio** [comment]
It’s showing in KB/s at low speed and MB/s at higher

**Comment by typhoon71** [comment]
migth be like that, it used different units - which is why I asked for the ability to use just one.
I asked for KB/s in the UI because bit/s wasn too small, and mixed was confusing.
Selectable (bit/s, KB/s, MB/s, ...) could have been good too - as an option.

**Comment by remlio** [comment]
but it’s already there. when the switch is on, then the speed is displayed in bit/s up to 999 bits, in kb/s up to 999 kbit, in mb/s up to 999 mbit etc. and when the switch is off, then the speed is displayed in B/s the same way: up to 999 b in B/s, up to 999 KB in KB/s, up to 999 in MB/s etc. Idk why I would need to enable the display mode, for example, in gigabytes per second when the current speed is in kilobytes per second. to see something like 0.005 GB/s there or why else?

**Comment by typhoon71** [comment]
Maybe my speeds are just near the end of one unit interval, so too big for the lower end and just right for the nearest end - making everything higher not relevant?
Whatever, I'm closing this.
