### ISSUE TITLE
Impossible to return to previous application

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#142]
Test case:
1. Click torrent file attachment in telegram (probably same behavior in any other app)
2. Torrent file will be opened in transmissionic
3. Now try to go back (with button or swipe) - it's impossiple to return to telegram. You have to press home button and open telegram from scratch.

As I see it, tranmissionic does not handle back action, like chrome browser for example.

**Comment by 6c65726f79** [comment]
Thank you for reporting this issue, I've encountered this bug before but I wasn't sure where it came from.
I was planning to rework the back button handling in the next version, so I will try to fix this bug at the same time.

**Comment by 6c65726f79** [comment]
This is fixed in [v1.1.8](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.8), and the back button should work better in browsers now.
