### ISSUE TITLE
Link in torrent comment

### ISSUE THREAD

**Issue by FataZlity** [6c65726f79/Transmissionic#153]
Can you please make links in torrent-info  comment clickable?

web-ui

Thanks for work!

**Comment by 6c65726f79** [comment]
Yes no problem, I will add this in the next version. Thank you for the suggestion!

**Comment by 6c65726f79** [comment]
Changes applied in [v1.1.9](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.1.9).
