### ISSUE TITLE
Multiple torrent files upload?

### ISSUE THREAD

**Issue by journeym** [6c65726f79/Transmissionic#161]
Obvious feature supported by transmission default client

**Comment by 6c65726f79** [comment]
It was not a priority, but I will obviously add this possibility. I'll try to add it in version 1.2.0.

**Comment by journeym** [comment]
Thanks

**Comment by 6c65726f79** [comment]
Feature added in [v1.2.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.2.0)
