### ISSUE TITLE
ArchLinux support

### ISSUE THREAD

**Issue by tomasdeltell** [6c65726f79/Transmissionic#167]
Can you create Archlinux package for Transmissionic?

**Comment by 6c65726f79** [comment]
The deb installer for linux-amd64 does not working on Archlinux? I'm not familiar with Archlinux so I don't know what the recommended package format is, and I thought the deb format was supported.

**Comment by 6c65726f79** [comment]
You can now use the AppImage on any linux distribution with [v1.3.2](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.2), like described in the [Linux](https://github.com/6c65726f79/Transmissionic#linux) section.
