### ISSUE TITLE
Plural forms in russian translation 

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#169]
Hey, I've played with plural forms of nouns for Russian language and it seems something is broken. So here is part of **ru.json** file:

```
"torrent": {
        "one": "торрент",
        "few": "торрента",
        "many": "торрентов",
        "other": "торренты"
    }
```

As I see it - it should be translated as follows (pay attention to different endings in russian):

```
Number    English         Russian
=====     =======         =======
0         0 torrents      0 торрентов
1         1 torrent       1 торрент
2         2 torrents      2 торрента
3         3 torrents      3 торрента
4         4 torrents      4 торрента
5         5 torrents      5 торрентов
6         6 torrents      6 торрентов
7         7 torrents      7 торрентов
8         8 torrents      8 торрентов
9         9 torrents      9 торрентов
10        10 torrents     10 торрентов
11        11 torrents     11 торрентов
12        12 torrents     12 торрентов
13        13 torrents     13 торрентов
14        14 torrents     14 торрентов
15        15 torrents     15 торрентов
16        16 torrents     16 торрентов
17        17 torrents     17 торрентов
18        18 torrents     18 торрентов
19        19 torrents     19 торрентов
20        20 torrents     20 торрентов
21        21 torrents     21 торрент
22        22 torrents     22 торрента
23        23 torrents     23 торрента
24        24 torrents     24 торрента
25        25 torrents     25 торрентов
26        26 torrents     26 торрентов
27        27 torrents     27 торрентов
28        28 torrents     28 торрентов
29        29 torrents     29 торрентов
```

For larger numbers it will be similar as for 20-29. But I can only see "торрент" (for 1 torrent) and "торренты" (for all other cases) within UI. May be some settings should be tweaked to deal properly with plural forms?

**Comment by 6c65726f79** [comment]
Thank you for this detailed informations, I was confused about the one/few/many/other because I only know languages that use singular and plural, but now it all makes sense.
I'll try to use the [make-plural](https://www.npmjs.com/package/make-plural) package to handle this for all languages. It seems to work just fine, but for 0 it's says to use the "many" form, is that correct?

**Comment by depler** [comment]
Probably yes, I've updated table for zero

**Comment by depler** [comment]
"Длительность" would be a little bit shorter. Don't really think that period or session is substitute of duration in this case, what is usage context for that word?

**Comment by 6c65726f79** [comment]
It's used as a row name, to display the duration of a session:

![stats](https://user-images.githubusercontent.com/73540958/117343053-33b06580-aea4-11eb-86d3-f0d8bfd7e188.png)

**Comment by depler** [comment]
I see. There is word "Время", which means "Time". But "Длительность" is much better if it's short enough.

**Comment by 6c65726f79** [comment]
Ok so "Длительность" is perfect.

I still have some work to do before releasing the next version, so here is a preview if you want: [v1.2.0-dev](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.2.0-dev).

**Comment by 6c65726f79** [comment]
Changes applied in [v1.2.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.2.0), thank you again for your very useful help.
