### ISSUE TITLE
Torrent file is not opening from telegram

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#175]
Seems to be broken in latest release, version 1.1.9 is ok

**Comment by 6c65726f79** [comment]
Exact, good catch. This will be fixed in the next version very soon.

**Comment by 6c65726f79** [comment]
Fixed in [v1.2.1](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.2.1), thank you for reporting it and sorry for the inconvenience.
