### ISSUE TITLE
Associating labels with torrents

### ISSUE THREAD

**Issue by Rhyn** [6c65726f79/Transmissionic#213]
It would be a great addition to add the possibility to define labels with different defaults like download path, priority or speed limits. Which could then be applied when adding torrent files to download. It could serve as an one click solution to handle different type of downloads like movies or tv series

**Comment by 6c65726f79** [comment]
Good suggestion, I'll try to implement it, but the speed limit can't be set when adding a torrent, so I have to find another way to do it.

**Comment by 6c65726f79** [comment]
Feature added in [v1.3.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.0).
