### ISSUE TITLE
Inprove Accessibility

### ISSUE THREAD

**Issue by falisca** [6c65726f79/Transmissionic#231]
Thanks ofthe nature of Electron the native Windows App is almost accessible but not so easy to use, for example, with a screen-reader.
Could the accessibility of the App or the web UI be inproved? Example: adding hotkeys, labelling buttons and more generally using the web ARIA / WCAG guidelines, that I'm pretty sure Electron have inplemented.

**Comment by 6c65726f79** [comment]
I don't have much free time at the moment, but I will try my best to improve the accessibility as soon as I can. Thank you for citing a few examples, I will focus on those. And the changes will affect both the web ui and the electron app.

**Comment by 6c65726f79** [comment]
Changes applied in [v1.3.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.0), you can now use the app and web UI with the keyboard only and I've added some labels on icons. But some parts still need some work, so let me know if you still have difficulties using the app.
