### ISSUE TITLE
Windows App remove multiple torrents problem

### ISSUE THREAD

**Issue by journeym** [6c65726f79/Transmissionic#268]
When removing multiple torrents in Windows App there is an error "The object cannot be cloned"
in Web  gui everything is fine

Also, selecting multiple torrents is a pain, is there a chance you could add Shift-select multiple torrents?

**Comment by 6c65726f79** [comment]
Thank you for reporting this bug, it will be fixed in the next version.

And good idea for the Shift+Click, I will add this possibility, thanks for the suggestion.

**Comment by 6c65726f79** [comment]
Changes applied in [v1.3.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.0).

**Comment by journeym** [comment]
Wow, it's even updating automatically...
Great!

**Comment by 6c65726f79** [comment]
Unfortunately there was the same issue when selecting a preset in v1.3.0, so I only rebuilt the Electron app as it doesn't affect other platforms. So if you're planning to use the preset feature I recommand you to re-download the 1.3.0 version, sorry for the inconvenience.
