### ISSUE TITLE
Donate the possibility to change the deamon path on windows application

### ISSUE THREAD

**Issue by LuFo57** [6c65726f79/Transmissionic#29]
Hi, can you donate the possibility to change the path of the deamon path for the windows application please. Actually, the path is /transmission/rpc/ or my system don't accept the end slash. With Transmission Remote GUI I don't have any problem without the end slash, but I have an error with the end slash (404 not found NGINX).

I ask this because I can't change my system, it's included in the box from my ISP (Free with the Freebox Revolution)

Thanks in advance for your answer

**Comment by 6c65726f79** [comment]
Hi, it's already possible to set the path of the RPC in the "Server details" page. If you leave this field empty it will be `/transmisison/rpc/` by default.

But I will change the default value to `/transmisison/rpc` as it doesn't break the compatibility with classic installations of Transmisison, so it will also work with the Freebox by default. 

Thank you for this informations.

**Comment by 6c65726f79** [comment]
Changes applied in v1.0.2 : https://github.com/6c65726f79/Transmissionic/releases/tag/v1.0.2
