### ISSUE TITLE
Latest webUI can not add on macOS and iOS

### ISSUE THREAD

**Issue by FataZlity** [6c65726f79/Transmissionic#310]
Latest webUI 1.31 can not add on macOS and iOS

on iOS when try to add torrent file its grey and can not choose

on MacOS when try to add torrent file nothing happens 

in 1.1.9 all works fine

Please help

**Comment by 6c65726f79** [comment]
It seems like Apple considers torrent files as text files, which break mimetype verification.
This will be fixed in the 1.3.2 release, thank you for reporting this issue.

**Comment by 6c65726f79** [comment]
Can you confirm that it works in the [1.3.2-dev](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.2-dev) pre-release?

**Comment by 6c65726f79** [comment]
Issue probably fixed in [v1.3.2](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.2).
