### ISSUE TITLE
Queue size cannot be changed

### ISSUE THREAD

**Issue by depler** [6c65726f79/Transmissionic#386]
Steps to reproduce with webui:

1. Change queue size in settings, click save
2. Refresh webui page - value is not changed.

Probably some other settings are also affected

**Comment by 6c65726f79** [comment]
Thank you for reporting this bug! It will be fixed in the 1.4.0 release, I will check if there are similar bugs.

**Comment by depler** [comment]
Any updates so far?

**Comment by 6c65726f79** [comment]
[v1.4.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.4.0) is finally here, thank you for your patience!
