### ISSUE TITLE
webui Filters show number of torrents

### ISSUE THREAD

**Issue by jiangjiangflies** [6c65726f79/Transmissionic#613]
First of all, thank you for developing such an amazing transmission webui. It is the best webui I've ever used! It's a super cool webui on iOS Safari!
Can you add a feature which can show the number of torrents in **Filters**（All, Active,Downloading,etc）. In **Trackers** section, it can show the number of torrents. Can you do this in **Filters** section? Thanks!
![1](https://user-images.githubusercontent.com/16556935/142798449-5a4bc850-b196-4554-b32e-b7ca044dd20e.jpg)
![2](https://user-images.githubusercontent.com/16556935/142798336-ad815d87-294f-4d8f-8957-de77bd1437c5.jpg)

**Comment by 6c65726f79** [comment]
Thanks for the compliment, I'm glad you like it!
I'll try to add this in the next version, but I have to find a way without using too much resources, as the number of torrents per filter must be calculated at each refresh. This could slow down the app with many torrents.

**Comment by 6c65726f79** [comment]
Feature added in [v1.5.1](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.5.1), thank you for your suggestion.
