### ISSUE TITLE
Chinese (simplified) translation updated

### ISSUE THREAD

**Issue by jiangjiangflies** [6c65726f79/Transmissionic#622]
Hi, I improved Chinese (simplified) translation and corrected some oblivious mistakes. Could you update the locale in the next release? 
Thanks!

**Comment by 6c65726f79** [comment]
Hi, yes of course, I'll try to release it soon. Thank you for your contribution.

**Comment by 6c65726f79** [comment]
New translations included in [v1.5.2](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.5.2).
