### ISSUE TITLE
Open torrents from Chrome Os (Chrome Os)

### ISSUE THREAD

**Issue by Steve2Go** [6c65726f79/Transmissionic#663]
Hi there, love the app, it's simply the best of its type in my opinion. I use it on android and windows.
In chrome os, it fails to open torrent files downloaded using the built in chrome browser.
Another android app FE explorer does offer to open them so it should be possible, I suspect it may be a case of adding some info on the manifest.

**Comment by Steve2Go** [comment]
For clarity, I'm speaking of the android app, running on chrome os.

**Comment by 6c65726f79** [comment]
Hi, thank you for your interest and for reporting this issue. I don't really see why it works with FE explorer and not with chrome, but I'll try my best to solve it. I'll let you know if I need you to test the update before publishing it.

**Comment by Steve2Go** [comment]
Awesome, thank you.
So opening from a chrome download I get offered to open in Fe explorer, but
not Transmissionic.

Have a great holiday season :)

**Comment by 6c65726f79** [comment]
And can you open the torrent file with Transmissionic from FE explorer ?

Thanks, you too!

**Comment by Steve2Go** [comment]
No, it's not offered.

But I can open the file manually from Transmissionic.

My first guess is that registering a file type for chrome os is additional
to registering for Android.

**Comment by 6c65726f79** [comment]
Ok thanks. 

Yes, that's probably the problem, I'll try to find documentation about that.

**Comment by 6c65726f79** [comment]
So, I haven't found any documentation on this, it's more likely a bug in Chrome OS. Luckily, I've found a workaround that is also used by FE explorer, so it may solve the problem: [LibreOffice/online/android/app/src/main/AndroidManifest.xml](https://github.com/LibreOffice/online/blob/d0edfeabbdc969a9a66cf90976a63c2f4403a6d3/android/app/src/main/AndroidManifest.xml#L119-L129)

I'll try to implement it in the next few days when I have some free time.

**Comment by Steve2Go** [comment]
Amazing.

Do you have a donation link?

Perhaps you could consider an in app purchase to donate, it's a great app,
on so many platforms.

**Comment by 6c65726f79** [comment]
No, not yet. But I'll consider creating one if you really want to give me a donation once I fixed the issue, this would be greatly appreciated! Thank you for the proposal.

**Comment by 6c65726f79** [comment]
Here is the pre-release that include the fix: [v1.5.3-dev](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.5.3-dev)

Can you confirm if this works? Thanks.

**Comment by Steve2Go** [comment]
Perfect!

That did it.

Thanks heaps for all your research and fix.

**Comment by 6c65726f79** [comment]
Nice, I'll release the new version tomorrow, thanks for testing it.

**Comment by 6c65726f79** [comment]
[v1.5.3](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.5.3) is published and available on the Play Store.

I've also created an account buymeacoffee.com, but my account is not yet approved. I'll add the sponsor button on GitHub when I get approved.
