### ISSUE TITLE
missing verifying filter

### ISSUE THREAD

**Issue by jiangjiangflies** [6c65726f79/Transmissionic#683]
Hi,
When transmission verifies local files, there is no verifying filter displaying.

**Comment by 6c65726f79** [comment]
Hi,
Just to be sure, you want a filter in the sidebar to show the verifying torrents, right?

**Comment by jiangjiangflies** [comment]
> Hi, Just to be sure, you want a filter in the sidebar to show the verifying torrents, right?

Yes,exactly!

**Comment by 6c65726f79** [comment]
Ok no problem, I'll add this as soon as I can. Thank you for suggesting it.

**Comment by jiangjiangflies** [comment]
thanks!

**Comment by 6c65726f79** [comment]
Feature added in [v1.5.5](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.5.5).
