### ISSUE TITLE
Safari extension for iOS 

### ISSUE THREAD

**Issue by aptonline** [6c65726f79/Transmissionic#689]
Recently came across this tweet and thought it might be useful if you wanted to port to an iOS Safari extension.

https://twitter.com/jensimmons/status/1483885578655608842?s=21

**Comment by 6c65726f79** [comment]
Thank you for sharing this, unfortunately the Web UI is not a browser extension, so I don't think it will work.

But the frameworks I use (Ionic and Capacitor) allows to build an iOS app, so it shouldn't be too hard to release the app for iOS. The main problem is that I don't have an Apple developer account and I'm not planning to pay for it, so I won't be able to sign the app. The best solution would be to find someone who has an Apple developer account and who would be willing to publish the application for me.

**Comment by aptonline** [comment]
There are alternative solutions if you are wanting to get an app out into the hands of iOS users.
 https://altstore.io/

**Comment by 6c65726f79** [comment]
Thanks, I didn't know this method. I knew Cydia Impactor but you need a developer account since 2019.

The expiration after 7 days is rather annoying, but it's better than nothing. I will try to build the app for iOS, but it will take me some time because I'm not familiar with iOS development.

**Comment by aptonline** [comment]
It’s not too much of an issues as it’s auto refreshes when your device in on the same wifi network. Works really well.

**Comment by aptonline** [comment]
Btw happy to test 👍.

**Comment by 6c65726f79** [comment]
> Works really well.

Ok I see, good news.

> Btw happy to test 👍.

Thanks, I'll let you know when I've managed to build the IPA.

**Comment by jiangjiangflies** [comment]
Waiting for iOS app, too!

**Comment by aptonline** [comment]
Looks like at some point you won’t have to go through the App Store.
https://9to5mac.com/2022/02/03/app-store-open-markets-act-senate-advance/

**Comment by 6c65726f79** [comment]
Awesome! Let's hope it doesn't take years to be voted and that this will apply outside of the US as well.

**Comment by 6c65726f79** [comment]
I've managed to get the app running in an emulator. Everything seems to be working properly, so I'll try to build the IPA very soon so you can test it on real hardware.

![ios screenshots](https://user-images.githubusercontent.com/73540958/153085926-7b9217e2-6a86-424a-afdf-aa8f19938efe.png)

**Comment by jiangjiangflies** [comment]
I tested ipa, awesome！But this is a minor annoying error message if I entered wrong credentials (see the second image).
![微信图片_20220212155501](https://user-images.githubusercontent.com/16556935/153702686-d80569b2-d9a5-4e76-b040-0c02c14e6ac8.jpg)
![微信图片_20220212155511](https://user-images.githubusercontent.com/16556935/153702744-a9c02f29-238b-4410-bfe9-e46baa0cbdbe.jpg)

**Comment by aptonline** [comment]
Congratulations 🎉 managed to side-load with AltStore and it’s working well in first test.

Will do some further testing and let you know if I spot anything 👍.

**Comment by 6c65726f79** [comment]
Perfect! Thanks for testing it. I still have some improvements to make on other platforms so the final version won't be released until next week.

> But this is a minor annoying error message if I entered wrong credentials

Yes I've noticed it too, this will be fixed in the final release.

**Comment by aptonline** [comment]
Not a bug but is there anyway to register magnet:// with the system so that magnet links can be recognised in Safari?

**Comment by 6c65726f79** [comment]
It should works, it worked when I tested on the emulator, what version of iOS are you using?

**Comment by aptonline** [comment]
iOS 15.3.1. Ok so it may be down to another app (DS Manager Pro) on my iPhone is also registered for magnet://. Not found a way to choose which one take precedent 🤔.

**Comment by aptonline** [comment]
Oh well will have to wait for another iOS update to address that hopefully.

**Comment by 6c65726f79** [comment]
I'm not sure if they plan to change this behavior, as URL scheme is supposed to be unique for each app. If you're using DS Manager Pro to handle another type of scheme than magnet, I think you can install Transmissionic first and then reinstall the other app, the magnet links should open with Transmissionic.

**Comment by aptonline** [comment]
There are always going to be situation where you want/need the url scheme to handle ‘generic’ types like magnet:// as that shouldn’t be titled to a specific app. Much like Apple did for http:// allowing you to have another browser over the default Safari app.
![992BAF4C-62AF-4113-870F-F59EF402A946](https://user-images.githubusercontent.com/190136/153721335-59ed3557-0b57-4cd1-96f8-d4a6a0ea2684.jpeg)

**Comment by 6c65726f79** [comment]
I fully agree, this is what Google did with Android, but knowing that this problem has been present since at least 2012, I don't know if this will change soon. Let's hope! The last advice I could give is to switch to Android, but it depends on your preferences 😄

![Screenshot_20220212-185135](https://user-images.githubusercontent.com/73540958/153722380-5a65897b-3671-4825-a2dd-5eca4ea8b8f0.png)

**Comment by 6c65726f79** [comment]
New version published: [v1.6.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.6.0)

Thank you again for your help!
