### ISSUE TITLE
Sort by folders

### ISSUE THREAD

**Issue by m0d3rnX** [6c65726f79/Transmissionic#733]
**Describe the feature you'd like**
Having the ability to sort by folder will make it easier to get rid of a type of downloads or seeing how they're doing right now when they're across multiple trackers.

**Describe a visual implementation**
Just like you're doing it with sort by tracker

**Comment by 6c65726f79** [comment]
For this feature I have a problem. There's not enough space in the sidebar to display the full path of a folder, so I have to show only the folder names, but there may be several folders with the same name, which would be problematic.
One solution would be to add a modal to select the folder to sort by. Does that sound good to you?
