### ISSUE TITLE
Use the last settings by default

### ISSUE THREAD

**Issue by m0d3rnX** [6c65726f79/Transmissionic#734]
**Describe the feature you'd like**
You're having to change the setting everytime when you add couple of single torrents, even if it could use the same settings as the one before.

So instead of going back to the default folder, use the last settings.
I don't think this creates an issue, it just could potentially save you a click for every file.

**Comment by 6c65726f79** [comment]
Feature added in [v1.6.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.6.0). Thank you for your suggestion.
