### ISSUE TITLE
Option for a tighter display of the entries

### ISSUE THREAD

**Issue by m0d3rnX** [6c65726f79/Transmissionic#735]
**Describe the feature you'd like**
12 torrents a time for a 1080p screen with default DPI on Windows is quite a rich interface, it's fine as a default option, but a tighter option would be nice to get a better overview and save some scrollingwork.

**Describe a visual implementation**
Not using multiple lines for an entry might work

**Comment by 6c65726f79** [comment]
The problem with displaying an entry on a single line is that there is not enough space on small screens like Android or iOS.

So either I display the entries on a single line only on large screens, or I add a condensed mode for all screen sizes that display the entries on two lines with the progress bar in background. In both cases, I think I can reduce the size by half.

**Comment by 6c65726f79** [comment]
Feature added in [v1.6.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.6.0). Thank you for your suggestion.
