### ISSUE TITLE
Support Directory Filter 

### ISSUE THREAD

**Issue by jiangjiangflies** [6c65726f79/Transmissionic#772]
It would be nice if there is a download **Directory** filter in the side bar. I have multiple download directories, so it would be cool to see the information of the torrents in those different directories. Besides, I hope it can show the torrent size of each filter, not just the number of torrents. Below is the screenshot of [Transmission Web Control](https://github.com/ronggang/transmission-web-control). 
Thanks!
![1](https://user-images.githubusercontent.com/16556935/154613280-6452571f-a5e3-4ecc-bd99-4effd10d04ad.png)

**Comment by 6c65726f79** [comment]
You can already filter by directory with the search bar, for example if you search for `/home/wwwroot/`, it will return all torrents in this directory.

And for the total size by filter, I'll try to add the total size of the torrent list next to the torrent count at the top of the list.

**Comment by 6c65726f79** [comment]
> But it should be more explicit if there is a directory filter, particularly convenient for multiple different download directories

The problem is that there's not much space available in the sidebar, especially on mobile devices, so it is difficult to display a directory tree.

**Comment by 6c65726f79** [comment]
Torrent list size added in [v1.6.1](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.6.1), thank you for your suggestion.

I'll reopen this issue if I find a way to implement the directory tree.

**Comment by abubaca4** [comment]
> I'll reopen this issue if I find a way to implement the directory tree.

Please look at [Torrnado](https://play.google.com/store/apps/details?id=com.gabordemko.torrnado) UI. For me now it the best sorting and filtering UI for transmission in mobile.
Dir tree in full not needed, you can left only different path.
Like this
/mnt/data/audio
/mnt/data/video/anime
/mnt/data/video/films
become
audio
video/anime
video/films

**Comment by jiangjiangflies** [comment]
I also tried [Torrnado](https://play.google.com/store/apps/details?id=com.gabordemko.torrnado) and the way it display Filters, Trackers, and Directories is exactly what I want. However, I prefer transmissionic UI. Three years past, don't know if the author is still interested in implementing this feature.
