### ISSUE TITLE
Alternative speeds scheduler

### ISSUE THREAD

**Issue by zagi988** [6c65726f79/Transmissionic#881]
Hi. First of all, great work! UI really looks great.
BUT, one thing missing, at least that I noticed.

Alternative speeds can be scheduled from when to when they are supposed to be active.
This is not possible to do in this GUI. For example, Flood can do it.

Is there a chance this gets implemented soon?

**Comment by 6c65726f79** [comment]
Hi, thank you for your interest in my project! That's right, I forgot to implement this feature. I'll try to add it in the next version as soon as I can. Thank you for pointing this out.

**Comment by zagi988** [comment]
Thanks!

**Comment by 6c65726f79** [comment]
Feature added in [v1.7.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.0), thank you again for suggesting it!
