### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource when adding a new server

### ISSUE THREAD

**Issue by sotiris-bos** [6c65726f79/Transmissionic#885]
**Describe the bug**
Hello, I am running transmission from linuxserver.io/transmission on docker. I have two containers running, my old one with the default interface and the new one with transmissionic.

When I am trying to add my old server to my new, I get this error as seen in the title. Adding the old server with the same settings to an Android Transmissionic client shows no errors and everything loads up just fine.

Using Chrome 99.0.4844.74, instead of the error mentioned above, I get `Unable to reach host`.

**Platform:**
 - OS: Linux Docker, Linuxserver.io transmission image, Transmissionic v1.6.2
 - Browser: Firefox 98.0.1

**Comment by 6c65726f79** [comment]
Hello, thank you for reporting this bug. This is most likely an issue with the same origin policy, you can't use the web UI to connect to another host, this is a browser limitation.

You can try to start chrome with these three arguments: `--disable-web-security --disable-gpu --user-data-dir=~/chromeTemp`, it should works. But you shouldn't use chrome with these arguments for security reasons.

So you have two solutions:
- Install transmissionic on your old server
- Use the desktop client for Windows or Linux to connect to your old server

**Comment by sotiris-bos** [comment]
Thank you for your swift reply! Indeed you are correct, running Chrome with the options above does let me add the old server.

That is a shame, I was wishing that I could manage both servers through one Web UI.

I know this question is out of scope of this service but do you happen to know if this would work if both servers were behind a reverse proxy? I will go ahead and try it anyways, I just don't have the time to set it up at the moment.

Thank you again for your time, I am closing this issue.

**Comment by 6c65726f79** [comment]
You're welcome!

Yes I forgot to mention this solution, you can set up a reverse proxy on your old server and enable CORS on the proxy ([example](https://chriscarey.com/blog/2014/06/13/apache-proxy-with-cors-headers/)).

**Comment by sotiris-bos** [comment]
Perfect! I will try it as soon as I find some time and report back with my findings and setup, in case someone else finds it useful.

Thank you again!

**Comment by sotiris-bos** [comment]
> You're welcome!
> 
> Yes I forgot to mention this solution, you can set up a reverse proxy on your old server and enable CORS on the proxy ([example](https://chriscarey.com/blog/2014/06/13/apache-proxy-with-cors-headers/)).

Hello again, I am making some good progress on this, however I am having a bit of an issue and I think it is due to transmissionic.

Do you have the `rpc-url` hardcoded as `transmission` somewhere in transmissionic? I am using nginx for the proxy and I have to change the `rpc-url` on one of the servers. If I change the `rpc-url` to anything else other than `transmission` (like `transmission1` or `transmission_private`), I get a:

`JSON.parse: unexpected character at line 1 column 1 of the JSON data` on Firefox

and

`Unexpected token < in JSON at position 0` on Chrome.

**Comment by 6c65726f79** [comment]
Thank you for your feedback! You can already create a file named `default.json` in the root folder of the web UI to overwrite the default settings, as described [here](https://github.com/6c65726f79/Transmissionic#default-settings). But for now, you can't overwrite the default server, so I'll try to add this possibility in the next version.

No need to open a new issue, I'll keep this one open until it's resolved.

**Comment by 6c65726f79** [comment]
You can now define default servers in `default.json` like described [here](https://github.com/6c65726f79/Transmissionic#web-ui-2) in [v1.7.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.0). Thank you for suggesting it!
