### ISSUE TITLE
Replace flag icon png with their Unicode equivalent

### ISSUE THREAD

**Issue by hacketiwack** [6c65726f79/Transmissionic#895]
**Describe the feature you'd like**
Currently the flags are statically available as PNG files.
It would be easier not to maintain these flags in the code base and use their Unicode equivalent.

**Describe a visual implementation**
Visually, the flags would be represented like this: 🇺🇸🇫🇷🇨🇰 🇨🇭🇳🇵...

**Additional context**
More information [here](http://xahlee.info/comp/unicode_flags.html)

**Comment by 6c65726f79** [comment]
Thank you for your suggestion! I'll see what I can do.

**Comment by hacketiwack** [comment]
Some more information [here](https://stackoverflow.com/questions/30494284/android-get-country-emoji-flag-using-locale).

**Comment by 6c65726f79** [comment]
I've done some testing, and it doesn't work on all devices. Some desktop browsers don't display emoji correctly :

![screenshot](https://user-images.githubusercontent.com/73540958/165357075-ccfb8d30-bb41-4db5-bc30-84eb20ab9024.png)

So I can't use this method for now.
