### ISSUE TITLE
Feature Requests - Delete torrent & Select Server

### ISSUE THREAD

**Issue by Steve2Go** [6c65726f79/Transmissionic#995]
Hi there.
Would you consider adding an option to delete the local torrent on Android & Windows when adding the torrent?
Another feature in other clients it the option to select which server you're uploading to when adding. Not a big one as currently I open the client first and choose, but it would be a nice touch.

Thanks for all your hard work - I use this across platforms, and love it.

**Comment by 6c65726f79** [comment]
Hi,
I won't be able to implement the feature to delete the local torrent on all platforms, so I'm not sure to add this feature. But the server selection when adding a torrent is a good idea, I'll try to add as soon as I can.

Thank you for you suggestions!

**Comment by 6c65726f79** [comment]
You can now select the server when adding a torrent in [v1.7.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.7.0), thank you again for suggesting it.
